### ISSUE TITLE
Forces facebook to type right to left, and messes with typing on youtube comments as well

### ISSUE THREAD

**Issue by rugabunda** [Muzilos/BDS-firefox-extension#1]
prevents typing in facebook (forces type right to left) and messes with typing on youtube comments as well, after typing the first letter in a youtube comment, it moves the cursor to the beginning of the line, messing up typing.

at the moment it makes anti satanic activism more difficult online, will update review when this is fixed

FF 77.0.1

**Comment by Muzilos** [comment]
Bug has been addressed in the latest release, please update your extension once available.
